#!/bin/bash
# Shell-script: final version

script_name="bash-lab"
version="1.0"
report_file="report.txt"
error_file="error.log"

print_usage() {
	echo "Usage: $0 <mode> <log-file>"
	echo
	echo "Modes:"

	for mode_name in info preview scan help; do
		echo "- $mode_name"
	done

	echo
	echo "Examples."
	echo "  $0 info sample.log"
	echo "  $0 preview sample.log"
	echo "  $0 scan sample.log"
	echo "  $0 report sample.log"
}

err() {
 	echo "Error: $1"
	exit 1
}

require_log_file() {
	local mode="$1"
	local file="$2"

	if [ -z "$file" ]; then
		err "log file is required for mode: $mode"
	fi

	if [ ! -f "$file" ]; then
		err "file not found: $file"
	fi

	if [ ! -r "$file" ]; then
		err "file is not readable: $file"
	fi
}

show_info() {
	local file="$1"
	local line_count

	line_count=$(wc -l < "$file")

	echo "$script_name version $version"
	echo "Target file: $file"
	echo "Lines: $line_count"
}

show_preview() {
	local file="$1"
	local limit=5
	local counter=0
	local line

	while IFS= read -r line; do
		counter=$((counter + 1))
		echo "$counter: $line"

		if [ "$counter" -ge "$limit" ]; then
			break
		fi
	done < "$file"
}

scan_ips() {
	local file="$1"

	grep -Eo '[0-9.]+' "$file" |
		awk -F. '
			NF != 4 { next }

			{
				for (octet = 1; octet <= 4; octet++) {
					if ($octet !~ /^[0-9][0-9]?[0-9]?$/ || $octet > 255) {
						next
					}
				}

				print
			}
		' |
		sort -u
}

make_report() {
	local file="$1"

	{
		echo "Report for: $file"
		echo "Generated by: $script_name $version"
		echo "Lines: $(wc -l < "$file")"
		echo
		echo "Unique IP-like strings:"
		scan_ips "$file"
	} > "$report_file" 2> "$error_file"

	echo "Report saved to: $report_file"
	echo "Errors saved to: $error_file"
}

mode="$1"
target_file="$2"

case "$mode" in
	help)
		print_usage
		;;
	info)
		require_log_file "$mode" "$target_file"
		show_info "$target_file"
		;;
	preview)
		require_log_file "$mode" "$target_file"
		show_preview "$target_file"
		;;
	scan)
		require_log_file "$mode" "$target_file"
		scan_ips "$target_file"
		;;
	report)
		require_log_file "$mode" "$target_file"
		make_report "$target_file"
		;;
	*)
		err "unknown mode: $mode"
		;;
esac
